name: CI Learning

on:
  push:
    branches:
      - ci-learning
jobs:
    stage-1:
        runs-on: ubuntu-latest
        steps:
            - name : Understand the runner
              run: |
                echo "Hello from GitHub Actions"
                echo "Machine:"
                uname -a
                echo "Current directory:"
                pwd
            - name: Checkout source code
              uses: actions/checkout@v3
            - name: Show repository files
              run: |
                pwd
                ls -la
            - name: Setup Python
              uses: actions/setup-python@v7
              with:
                python-version: '3.11'

            - name: Check Python version
              run: |
                python --version
                pip --version

            - name: Install dependencies
              run: |
                pip install -r requirements.txt
                pip install pytest httpx

            - name: Run tests
              env:
                TEST_MODE: "true"
                PYTHONPATH: .
              run: |
                pytest -q
            - name: Build Docker image
              run: |
                docker build -t production-rag:ci .
            - name: Start Docker container
              run: |
                docker run -d \
                --name production-rag-ci \
                -p 8080:8080 \
                -e TEST_MODE=true \
                production-rag:ci

            - name: Health check
              run: |
                for i in {1..20}; do
                    if curl --fail http://localhost:8080/health; then
                    echo "Application healthy"
                    exit 0
                    fi

                    sleep 1
                done

                docker logs production-rag-ci
                exit 1


            - name: Cleanup
              if: always()
              run: |
                docker rm -f production-rag-ci || true
    stage-2:
        runs-on: ubuntu-latest
        steps:
            - name : Understand the runner
              run: |
                echo "Hello from GitHub Actions"
                echo "Machine:"
                uname -a
                echo "Current directory:"
                pwd
        